### PR TITLE
Bumped version to 1.2.0

### PR DESCRIPTION
**Pull request by carmelogallo**
This new version bumped Kotlin version to 1.6.0

### CODE REVIEW

**Review by avdyushin — APPROVED** [review]
:+1:

**Comment by KamiSempai** [comment]
@cikpis Thank you for pull request. Could you change library version to 1.1.7. There is no need to bump minore version, cause the library hasn't any changes since 1.1.6.

**Comment by carmelogallo** [comment]
Hi @KamiSempai, the reason why I've changed it to a major one is that the version of Kotlin is also a major which introduce some breaking changes. On versioning side it should follow the dependency. Do you still want to have me to change it to `1.1.7`?

**Comment by KamiSempai** [comment]
@cikpis If Kotlin hasn't changes that forced to use this library in the different way, no need to bump minor version.

**Comment by carmelogallo** [comment]
@KamiSempai Alright, done

**Comment by carmelogallo** [comment]
@KamiSempai any updates on this?

**Comment by carmelogallo** [comment]
@KamiSempai thanks for merging it. Could you also create the tag `1.1.7` and release it? Thanks

**Comment by KamiSempai** [comment]
@cikpis It looks like there are problems in the Nexus repository manager. I keep getting "ERROR 405". I'll try to repeat publication later.

**Comment by carmelogallo** [comment]
Hi @KamiSempai, any updates on this?

**Comment by KamiSempai** [comment]
@cikpis I have release version 1.1.8 for Kotlin 1.6.10.

**Comment by carmelogallo** [comment]
That's even better 👍

**Pull request merged**
